### ISSUE TITLE
remove magic values

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/node-raknet#10]
There are still a few hardcoded values in the code. It works so it's not a big deal but better generate them properly (example : serverid)

**Comment by mhsjlw** [comment]
does protodef support default values?

**Comment by rom1504** [comment]
what do you mean by that ?

**Comment by rom1504** [comment]
I'm not talking about the "magic" value of raknet here.

**Comment by mhsjlw** [comment]
ah, I misunderstood, sorry.

**Comment by rom1504** [comment]
remaining here:
* [ ] client/server id
* [ ] ping number

**Comment by rom1504** [comment]
done
