### ISSUE TITLE
add error/warning when there are trailing bytes in the encapsulated packet

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/node-raknet#26]

**Comment by rom1504** [comment]
test with https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET/Net/MCPE%20Protocol.xml#L174 which is apparently actually 3 bytes (according to yawkat)

**Comment by mhsjlw** [comment]
`PartialReadError` is now thrown from ProtoDef
