### ISSUE TITLE
Could we just wrap the "official" C++ implementation in Node bindings?

### ISSUE THREAD

**Issue by geekytime** [mhsjlw/node-raknet#29]
I think this is the "official" RakNet implementation that Minecraft uses?

https://github.com/facebookarchive/RakNet

Could we create easier high-level Node bindings for that C++ api?

**Comment by rom1504** [comment]
@mhsjlw worked on that

**Comment by mhsjlw** [comment]
Yeah, we can absolutely do it. That is out of the scope for this module, it would be separate. May I ask why this is necessary and/or your use case?

**Comment by geekytime** [comment]
I'm frustrated by the few server options available for Minecraft that support bedrock 1.2, and surprised to see that so many of them re-implement RakNet from scratch.

You had mentioned in another issue that you were considering re-writing parts of this module in native code, because you were worried parts might be too slow in JS. As I was looking at the C++ code to get an idea of how it worked, it struck me that a lot could be done with a relatively simple wrapper.

So I was just curious if anyone had tried this, and whether it seemed viable to people who are obviously way ahead of me in thinking about these things.

**Comment by mhsjlw** [comment]
RakNet is riddled with undiscovered security issues, has few optional features so the binary is bigger than it needs to be, these can be fixed of course, but the time is much better spent on a native port. However, I have spent time making a cleaner RakNet that is more compatible and cleans up a couple of things. I'd be happy to write bindings for it when I find the time.

**Comment by mhsjlw** [comment]
I'm going to close this as we've decided we are going to just fix this library.
